apiVersion: apps/v1
kind: Deployment
metadata:
  name: tower-defense-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tower-defense-game
  template:
    metadata:
      labels:
        app: tower-defense-game
    spec:
      containers:
        - name: tower-defense-game
          image: tower-defense-image
          ports:
            - containerPort: 8080
